module.exports = (componentName, version, date) => {
  return {
    content: `// Generated by EZReactComponents v.${version}
// on ${date}.
export interface ${componentName}Props {}`,
    extension: "types.ts"
  };
};