module.exports = (componentName, version, date) => {
  const content = `// Generated by EZReactComponents v.${version}
// on ${date}.
import React from "react";
import ${componentName} from "./${componentName}";

export default {
    title: "${componentName}"
};

export const Default = () => <${componentName}/>;`;

  return {
    content,
    extension: "stories.tsx"
  };
};