const { pascalToKebab } = require("../util/string.util");

module.exports = (componentName, version, date) => {
  const content = `// Generated by EZReactComponents v.${version}
// on ${date}.
import React from 'react';
import { ${componentName}Props } from './${componentName}.types';
import './${componentName}.scss';

const ${componentName}: React.FC<${componentName}Props>  = ({}) => {
    return <div className='${pascalToKebab(componentName)}'>${componentName}</div>;
};

export default ${componentName};`;

  return {
    content,
    extension: "tsx"
  };
};