module.exports = (componentName, version, date) => {
  const content = `// Generated by EZReactComponents v.${version}
// on ${date}.
import React from "react";
import { render } from "@testing-library/react";

import ${componentName} from "./${componentName}";
import { ${componentName}Props } from "./${componentName}.types";

describe("${componentName}", () => {
  let props: ${componentName}Props;

  const renderComponent = () => render(<${componentName} {...props} />);

  it("should render foo text correctly", () => {
    const { getByTestId } = renderComponent();

    const component = getByTestId("${componentName}");

    expect(component).toBeInstanceOf(HTMLElement);
  });
});`;

  return {
    content,
    extension: "test.tsx"
  };
};